<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<OutputPath>Output\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
		<!-- 将obj目录指向系统临时目录 -->
		<BaseIntermediateOutputPath>$(Temp)\$(MSBuildProjectName)</BaseIntermediateOutputPath>

  </PropertyGroup>

</Project>
